# Generated by Django 5.1.3 on 2024-11-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_alarm_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='song',
            field=models.FileField(blank=True, default='songs/Godzila.mp3', upload_to='songs/'),
        ),
    ]
